[package]
name = "cel-lsp"
version.workspace = true
edition.workspace = true

[dependencies]
cel-parser = { path = "../cel-parser" }
dashmap = "5.5"
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
regex = "1.10"
