[package]
name = "cel-core-types"
description = "CEL type system with parameterized types"
keywords = ["cel", "types"]
categories = ["development-tools"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
